apiVersion: v1
kind: Pod
metadata:
  name: volume-example
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello from Volume!' > /data/message && sleep 3600"]
    volumeMounts:
    - name: demo-volume
      mountPath: /data
  volumes:
  - name: demo-volume
    emptyDir: {}