apiVersion: v1
kind: Pod
metadata:
  name: hostpath-example
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Hello from HostPath Volume!' > /data/message && sleep 3600"]
    volumeMounts:
    - name: demo-volume
      mountPath: /data
  volumes:
  - name: demo-volume
    hostPath:
      path: /tmp/hostpath-demo
      type: DirectoryOrCreate