apiVersion: v1
kind: Pod
metadata:
  name: ebs-pod1
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "echo Hello from PV > /data/hello.txt && sleep 3600"]
    volumeMounts:
    - mountPath: "/data"
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: ebs-pvc