apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: myapp
    image: busybox
    command: [ "/bin/sh", "-c", "cat /etc/secret-volume/username; sleep 3600" ]

    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume

  volumes:
  - name: secret-volume
    secret:
      secretName: db-secret